app_terminal_tuimoji: pkg_resources moved to setuptools
So this needs injecting the setuptools package now to prevent this error:

> Traceback (most recent call last):
>   File "/usr/local/bin/tuimoji", line 5, in <module>
>     from tuimoji.tuimoji import main
>   File
> "/usr/local/pipx/venvs/tuimoji/pipx/venvs/tuimoji/lib/python3.12/site-packages/tuimoji/tuimoji.py",
> line 8, in <module>
>     from pkg_resources import resource_string
> ModuleNotFoundError: No module named 'pkg_resources'